apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-data
  namespace: default
spec:
  encryptedData:
    secret-info: AgBiWq7DNq8+ytVnfGOOjTss3GTY3FqcmzETZ7/bijb2xbEszPzSf/nSiykt90oTk+F+hGbhybpq6Nqq401iQxp9GFWtNyY1BmlqqYpGuxdTpxOw2v/yInp2M/S4sN9ulqc6kPjf6fg1rNVwmMRMOKsnELvxdJsyO24cuJGVCALpkhF5jkw5bZUv7yc0ScrajQ/hyM54VpP9hVE5jrG+ixgcTVU+3chwJ8GqLMU4r9frr0vEP1cTnRHP6hlhVAx6M7QFtPkIZ1dnOnVfjLs3d3bMcLjdZO53C711Q2Dim6y8FeVvU7sHhLGGKO9LtjPMSWA1kHPy6504fzRlMzL8ULILFtr2c6X6z5Ha7zVxy8HaQ6sAe3Mu2jchZeGIvExmuuKMIwJJRhshSi9Ym4zkWw+p/mIQgwz+QUeLKL0WZlxVS9gz2UVimMyA2FA11PA3dv3x8tS0Hy8pRV/CJLur32Qjv0DmRWh3YX/9v+j/r8lWt+IzlMKabsE9IVz8IQp/hgk+bfotrZpDbSMOVfiQhfoP8g+Vx7STmT6YMViC1uvCsQI1BKl8YX8P07Fr8WbhSUFJdILPVozkukwB8ebDM4e55LO8Dxd62bAnjXQsglrSXKbW7GO3xETQ6z+bdcWi5Bqprq/BG0uNTY+i7/jhwm+LB779wc3sY+HcdkfmlGry9HBdBZ3tA7lbZocOHQyJY290mlY67qxQm7M=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-data
      namespace: default


